//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ced.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ced.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Notes.
        /// </summary>
        public static string AdditionalNotes {
            get {
                return ResourceManager.GetString("AdditionalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Day.
        /// </summary>
        public static string AllDayEvent {
            get {
                return ResourceManager.GetString("AllDayEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ax Rec Id.
        /// </summary>
        public static string AxRecId {
            get {
                return ResourceManager.GetString("AxRecId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based Edition Translation could not found.
        /// </summary>
        public static string BasedEditionTranslationNotFound {
            get {
                return ResourceManager.GetString("BasedEditionTranslationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Stand Link.
        /// </summary>
        public static string BookStandUrl {
            get {
                return ResourceManager.GetString("BookStandUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        public static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to zoom.
        /// </summary>
        public static string ClickToZoom {
            get {
                return ResourceManager.GetString("ClickToZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-hosted.
        /// </summary>
        public static string CohostedEvent {
            get {
                return ResourceManager.GetString("CohostedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Email.
        /// </summary>
        public static string CorporateEmail {
            get {
                return ResourceManager.GetString("CorporateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not updated.
        /// </summary>
        public static string CouldNotUpdated {
            get {
                return ResourceManager.GetString("CouldNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Picture File.
        /// </summary>
        public static string CoverPictureFileName {
            get {
                return ResourceManager.GetString("CoverPictureFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Time.
        /// </summary>
        public static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code.
        /// </summary>
        public static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string Dates {
            get {
                return ResourceManager.GetString("Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DelegateCountries.
        /// </summary>
        public static string DelegateCountries {
            get {
                return ResourceManager.GetString("DelegateCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        public static string Director {
            get {
                return ResourceManager.GetString("Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director Email.
        /// </summary>
        public static string DirectorEmail {
            get {
                return ResourceManager.GetString("DirectorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayDate.
        /// </summary>
        public static string DisplayDate {
            get {
                return ResourceManager.GetString("DisplayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayOnGIMA.
        /// </summary>
        public static string DisplayOnGIMA {
            get {
                return ResourceManager.GetString("DisplayOnGIMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayOnITEAsia.
        /// </summary>
        public static string DisplayOnITEAsia {
            get {
                return ResourceManager.GetString("DisplayOnITEAsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayOnITEI.
        /// </summary>
        public static string DisplayOnITEI {
            get {
                return ResourceManager.GetString("DisplayOnITEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayOnITEModa.
        /// </summary>
        public static string DisplayOnITEModa {
            get {
                return ResourceManager.GetString("DisplayOnITEModa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayOnITETurkey.
        /// </summary>
        public static string DisplayOnITETurkey {
            get {
                return ResourceManager.GetString("DisplayOnITETurkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayOnTradeLink.
        /// </summary>
        public static string DisplayOnTradeLink {
            get {
                return ResourceManager.GetString("DisplayOnTradeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Edition.
        /// </summary>
        public static string EditEdition {
            get {
                return ResourceManager.GetString("EditEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        public static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition Description.
        /// </summary>
        public static string EditionDescription {
            get {
                return ResourceManager.GetString("EditionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition List.
        /// </summary>
        public static string EditionList {
            get {
                return ResourceManager.GetString("EditionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition Name.
        /// </summary>
        public static string EditionName {
            get {
                return ResourceManager.GetString("EditionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition No..
        /// </summary>
        public static string EditionNo {
            get {
                return ResourceManager.GetString("EditionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editions.
        /// </summary>
        public static string Editions {
            get {
                return ResourceManager.GetString("Editions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name, Edition Name or Director Email.
        /// </summary>
        public static string EditionSearchBoxPlaceHolder {
            get {
                return ResourceManager.GetString("EditionSearchBoxPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition Summary.
        /// </summary>
        public static string EditionSummary {
            get {
                return ResourceManager.GetString("EditionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition has been updated.
        /// </summary>
        public static string EditionUpdated {
            get {
                return ResourceManager.GetString("EditionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition Venue.
        /// </summary>
        public static string EditionVenue {
            get {
                return ResourceManager.GetString("EditionVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Editions.
        /// </summary>
        public static string EventEditions {
            get {
                return ResourceManager.GetString("EventEditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Flag Picture.
        /// </summary>
        public static string EventFlagPictureFileName {
            get {
                return ResourceManager.GetString("EventFlagPictureFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Id.
        /// </summary>
        public static string EventId {
            get {
                return ResourceManager.GetString("EventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Names.
        /// </summary>
        public static string EventNames {
            get {
                return ResourceManager.GetString("EventNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Code, Master Name or Director Email.
        /// </summary>
        public static string EventSearchBoxPlaceHolder {
            get {
                return ResourceManager.GetString("EventSearchBoxPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Type.
        /// </summary>
        public static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event updated.
        /// </summary>
        public static string EventUpdated {
            get {
                return ResourceManager.GetString("EventUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExhibitorRetentionRate.
        /// </summary>
        public static string ExhibitorRetentionRate {
            get {
                return ResourceManager.GetString("ExhibitorRetentionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Map.
        /// </summary>
        public static string GoogleMap {
            get {
                return ResourceManager.GetString("GoogleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string Industry {
            get {
                return ResourceManager.GetString("Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Exhibitor Retention Rate.
        /// </summary>
        public static string InternationalExhibitorRetentionRate {
            get {
                return ResourceManager.GetString("InternationalExhibitorRetentionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Revenue.
        /// </summary>
        public static string InternationalRevenue {
            get {
                return ResourceManager.GetString("InternationalRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Revenue Currency Code.
        /// </summary>
        public static string InternationalRevenueCurrencyCode {
            get {
                return ResourceManager.GetString("InternationalRevenueCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Revenue (GBP).
        /// </summary>
        public static string InternationalRevenueGBP {
            get {
                return ResourceManager.GetString("InternationalRevenueGBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Revenue (Local Currency).
        /// </summary>
        public static string InternationalRevenueLocalCurrency {
            get {
                return ResourceManager.GetString("InternationalRevenueLocalCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Sqm Sold.
        /// </summary>
        public static string InternationalSqmSold {
            get {
                return ResourceManager.GetString("InternationalSqmSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Visitor Count.
        /// </summary>
        public static string InternationalVisitorCount {
            get {
                return ResourceManager.GetString("InternationalVisitorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is invalid.
        /// </summary>
        public static string KeyIsInvalid {
            get {
                return ResourceManager.GetString("KeyIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Exhibitor Retention Rate.
        /// </summary>
        public static string LocalExhibitorRetentionRate {
            get {
                return ResourceManager.GetString("LocalExhibitorRetentionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Revenue.
        /// </summary>
        public static string LocalRevenue {
            get {
                return ResourceManager.GetString("LocalRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Revenue Currency Code.
        /// </summary>
        public static string LocalRevenueCurrencyCode {
            get {
                return ResourceManager.GetString("LocalRevenueCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Revenue (GBP).
        /// </summary>
        public static string LocalRevenueGBP {
            get {
                return ResourceManager.GetString("LocalRevenueGBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Revenue (Local Currency).
        /// </summary>
        public static string LocalRevenueLocalCurrency {
            get {
                return ResourceManager.GetString("LocalRevenueLocalCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Sqm Sold.
        /// </summary>
        public static string LocalSqmSold {
            get {
                return ResourceManager.GetString("LocalSqmSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Count (Local).
        /// </summary>
        public static string LocalVisitorCount {
            get {
                return ResourceManager.GetString("LocalVisitorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo File.
        /// </summary>
        public static string LogoFileName {
            get {
                return ResourceManager.GetString("LogoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing Office Email.
        /// </summary>
        public static string ManagingOfficeEmail {
            get {
                return ResourceManager.GetString("ManagingOfficeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing Office Name.
        /// </summary>
        public static string ManagingOfficeName {
            get {
                return ResourceManager.GetString("ManagingOfficeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing Office Phone.
        /// </summary>
        public static string ManagingOfficePhone {
            get {
                return ResourceManager.GetString("ManagingOfficePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing Office Website.
        /// </summary>
        public static string ManagingOfficeWebsite {
            get {
                return ResourceManager.GetString("ManagingOfficeWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Code.
        /// </summary>
        public static string MasterCode {
            get {
                return ResourceManager.GetString("MasterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Name.
        /// </summary>
        public static string MasterName {
            get {
                return ResourceManager.GetString("MasterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPS Average Exhibitor.
        /// </summary>
        public static string NPSAverageExhibitor {
            get {
                return ResourceManager.GetString("NPSAverageExhibitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPS Average Visitor.
        /// </summary>
        public static string NPSAverageVisitor {
            get {
                return ResourceManager.GetString("NPSAverageVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPS Satisfaction Exhibitor.
        /// </summary>
        public static string NPSSatisfactionExhibitor {
            get {
                return ResourceManager.GetString("NPSSatisfactionExhibitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPS Satisfaction Visitor.
        /// </summary>
        public static string NPSSatisfactionVisitor {
            get {
                return ResourceManager.GetString("NPSSatisfactionVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPS Score Exhibitor.
        /// </summary>
        public static string NPSScoreExhibitor {
            get {
                return ResourceManager.GetString("NPSScoreExhibitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPS Score Visitor.
        /// </summary>
        public static string NPSScoreVisitor {
            get {
                return ResourceManager.GetString("NPSScoreVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Exhibiting Countries.
        /// </summary>
        public static string NumberOfExhibitingCountries {
            get {
                return ResourceManager.GetString("NumberOfExhibitingCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of International Delegates.
        /// </summary>
        public static string NumberOfInternationalDelegates {
            get {
                return ResourceManager.GetString("NumberOfInternationalDelegates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of International Exhibitors.
        /// </summary>
        public static string NumberOfInternationalExhibitors {
            get {
                return ResourceManager.GetString("NumberOfInternationalExhibitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of International Paid Delegates.
        /// </summary>
        public static string NumberOfInternationalPaidDelegates {
            get {
                return ResourceManager.GetString("NumberOfInternationalPaidDelegates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Local Delegates.
        /// </summary>
        public static string NumberOfLocalDelegates {
            get {
                return ResourceManager.GetString("NumberOfLocalDelegates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Local Exhibitors.
        /// </summary>
        public static string NumberOfLocalExhibitors {
            get {
                return ResourceManager.GetString("NumberOfLocalExhibitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Local Paid Delegates.
        /// </summary>
        public static string NumberOfLocalPaidDelegates {
            get {
                return ResourceManager.GetString("NumberOfLocalPaidDelegates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of National Groups.
        /// </summary>
        public static string NumberOfNationalGroups {
            get {
                return ResourceManager.GetString("NumberOfNationalGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Sponsors.
        /// </summary>
        public static string NumberOfSponsors {
            get {
                return ResourceManager.GetString("NumberOfSponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Visitor Countries.
        /// </summary>
        public static string NumberOfVisitorCountries {
            get {
                return ResourceManager.GetString("NumberOfVisitorCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office / Company Name.
        /// </summary>
        public static string OfficeOrCompanyName {
            get {
                return ResourceManager.GetString("OfficeOrCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Invitation Link.
        /// </summary>
        public static string OnlineInvitationUrl {
            get {
                return ResourceManager.GetString("OnlineInvitationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Registered Count.
        /// </summary>
        public static string OnlineRegisteredCount {
            get {
                return ResourceManager.GetString("OnlineRegisteredCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Registered Visitor Count.
        /// </summary>
        public static string OnlineRegisteredVisitorCount {
            get {
                return ResourceManager.GetString("OnlineRegisteredVisitorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Instance Dw Event Id.
        /// </summary>
        public static string PreviousInstanceDwEventId {
            get {
                return ResourceManager.GetString("PreviousInstanceDwEventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue Type.
        /// </summary>
        public static string RevenueType {
            get {
                return ResourceManager.GetString("RevenueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsors.
        /// </summary>
        public static string Sponsors {
            get {
                return ResourceManager.GetString("Sponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sqm Sold.
        /// </summary>
        public static string SqmSold {
            get {
                return ResourceManager.GetString("SqmSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopExhibitorCountries.
        /// </summary>
        public static string TopExhibitorCountries {
            get {
                return ResourceManager.GetString("TopExhibitorCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopVisitorCountries.
        /// </summary>
        public static string TopVisitorCountries {
            get {
                return ResourceManager.GetString("TopVisitorCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sponsorship Revenue Currency Code.
        /// </summary>
        public static string TotalSponsorshipRevenueCurrencyCode {
            get {
                return ResourceManager.GetString("TotalSponsorshipRevenueCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Revenue.
        /// </summary>
        public static string TotalSponsorshipRevenueGBP {
            get {
                return ResourceManager.GetString("TotalSponsorshipRevenueGBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Revenue.
        /// </summary>
        public static string TotalSponsorshipRevenueLocalCurrency {
            get {
                return ResourceManager.GetString("TotalSponsorshipRevenueLocalCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Time.
        /// </summary>
        public static string UpdateTime {
            get {
                return ResourceManager.GetString("UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User.
        /// </summary>
        public static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue Coordinates.
        /// </summary>
        public static string VenueCoordinates {
            get {
                return ResourceManager.GetString("VenueCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string VisitEndTime {
            get {
                return ResourceManager.GetString("VisitEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string VisitStartTime {
            get {
                return ResourceManager.GetString("VisitStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Times.
        /// </summary>
        public static string VisitTimes {
            get {
                return ResourceManager.GetString("VisitTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
