//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ced.DWStaging
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edition
    {
        public int DWEventID { get; set; }
        public string EventBEID { get; set; }
        public string EventMasterCode { get; set; }
        public string EventMaster { get; set; }
        public string EventRegion { get; set; }
        public string EventCountryName { get; set; }
        public string EventCity { get; set; }
        public string EventManagingOfficeName { get; set; }
        public string EventType { get; set; }
        public string EventIndustry { get; set; }
        public string EventSubIndustry { get; set; }
        public string EventFrequency { get; set; }
        public string EventName { get; set; }
        public string EventVenue { get; set; }
        public Nullable<int> EditionNo { get; set; }
        public Nullable<int> EventStartDate { get; set; }
        public Nullable<int> EventEndDate { get; set; }
        public string EventDirector { get; set; }
        public string EventBandClassification { get; set; }
        public Nullable<int> PreviousEditionDWEventID { get; set; }
        public string EventLongNameLocal { get; set; }
        public string EventLongNameInternational { get; set; }
        public string EventNameReporting { get; set; }
        public string EventDirectorEmail { get; set; }
        public string EventFYStart { get; set; }
        public string EventFYEnd { get; set; }
        public string EventActivity { get; set; }
        public string DirectorManagingOfficeName { get; set; }
        public string EVENTTYPEBEID { get; set; }
        public string EventBusinessClassification { get; set; }
        public string EVENTOWNERSHIPBEID { get; set; }
        public string EVENTOWNERSHIP { get; set; }
    }
}
